// This file is generated by Slice Machine. Update with care!

import About from './About';
import Contact from './Contact';
import Portfolio from './Portfolio';

export {
	About,
	Contact,
	Portfolio,
};

export const components = {
	about: About,
	contact: Contact,
	portfolio: Portfolio,
};
